# Setup
title:               Kevin Reichek
tagline:             ''
description:         '' 
url:                 http://kreichek.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kevin Reichek
  url:               https://twitter.com/kreichek
  email:             kevinreichek@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
